MIN_WORD_LENGTH = 1
MAX_WORD_LENGTH = 32
MAX_ATTEMPTS = 8


STATUS_IN_PROGRESS = 'in_progress'
STATUS_WON = 'won'
STATUS_LOST = 'lost'

STATUS_CHOICES = (
    STATUS_IN_PROGRESS,
    STATUS_WON,
    STATUS_LOST
)
